version: "3.9"

networks:
  public:   { driver: bridge }          
  internal: { driver: bridge, internal: true }  

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env.file
    environment:
      CHAT_HOST: tcpchat    # DNS = service name
      CHAT_PORT: "1337"
    depends_on:
      - tcpchat
    networks: ["public","internal"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8080)); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 10
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp

  tcpchat:
    build: ./tcpchat
    environment:
      KEY_HEX: "deadbeefcafebabe0011223344556677"
    ports: ["1337:1337"]                 
    networks: ["internal"]      

  rev-ssh:
    build:
      context: ./rev
      dockerfile: Dockerfile
    ports: ["2222:22"]                   
    networks: ["public"]                 
